simple_prognozer/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('country_page/<int:pk>/', mainapp.country_page, name='country_page'),
]

simple_prognozer/simple_prognozer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainapp.urls', namespace='main')),
]

simple_prognozer/mainapp/models.py
from django.db import models


class Continent(models.Model):
    continent = models.CharField(verbose_name='Continent',
                                 max_length=32,
                                 unique=True)


class Country(models.Model):
    country = models.CharField(verbose_name='Country',
                               max_length=128,
                               unique=True
                               )
    # Двухбуквенный код страны
    iso_alpha_2 = models.CharField(verbose_name='ISO 2',
                                   max_length=2,
                                   null=True
                                   )

    continent = models.ForeignKey(Continent,
                                  on_delete=models.DO_NOTHING,
                                  null=True)


class Subdivision(models.Model):
    country = models.ForeignKey(Country,
                                on_delete=models.DO_NOTHING,
                                )

    subdivision = models.CharField(verbose_name='Province, Region or City',
                                   max_length=128,
                                   null=True
                                   )

    # Альтернативное название страны/региона для поиска кол-ва населения
    alias_for_population = models.CharField(verbose_name='Alias',
                                            max_length=128,
                                            null=True
                                            )

    # FIPS только для US
    fips = models.IntegerField(verbose_name='FIPS US inner number',
                               null=True
                               )

    # Admin2 только для US
    admin2 = models.CharField(verbose_name='Admin2 County name. US only',
                              max_length=128,
                              null=True,
                              )

    # Широта
    lat = models.DecimalField(verbose_name='Latitude',
                              max_digits=19,
                              decimal_places=16,
                              null=True
                              )

    # Долгота
    longitude = models.DecimalField(verbose_name='Longitude',
                                    max_digits=19,
                                    decimal_places=16,
                                    null=True
                                    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['admin2', 'country', 'fips'],
                                    name='uq_subdivison')
        ]


class MainTable(models.Model):
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING)
    subdivision = models.ForeignKey(Subdivision,
                                    on_delete=models.DO_NOTHING,
                                    null=True
                                    )
    # Заболевшие
    confirmed = models.PositiveIntegerField(verbose_name='Confirmed',
)
    # Смерти
    deaths = models.PositiveIntegerField(verbose_name='Deaths',
                                         )
    # Выздоровления
    recovered = models.PositiveIntegerField(verbose_name='Recovered',
                                            )
    # Активные больные
    active = models.IntegerField(verbose_name='Active',
                                 null=True,
                                 )

    last_update = models.DateTimeField(verbose_name='Last update',
                                       )

    # Заболеваемость
    incidence_rate = models.DecimalField(verbose_name='Incidence rate',
                                         max_digits=25,
                                         decimal_places=16,
                                         blank=True,
                                         null=True,
                                         )
    # Соотношение Заболеваемости И Летальности в % на 100 000 человек
    case_fatality_ratio = models. \
        DecimalField(verbose_name='Case fatality ratio',
                     max_digits=25,
                     decimal_places=16,
                     default=0,
                     null=True
                     )

    region_population = models. \
        PositiveIntegerField(verbose_name='Region population',
                             default=0
                             )


class TimeSeries(models.Model):
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING)
    subdivision = models.ForeignKey(Subdivision, on_delete=models.DO_NOTHING,
                                    null=True)
    last_update = models.DateTimeField()
    # Заболевшие
    confirmed = models.PositiveIntegerField(verbose_name='Confirmed',
                                            default=0
                                            )
    # Смерти
    deaths = models.PositiveIntegerField(verbose_name='Deaths',
                                         default=0
                                         )
    # Выздоровления
    recovered = models.PositiveIntegerField(verbose_name='Recovered',
                                            default=0
                                            )

simple_prognozer/mainapp/views.py
from django.shortcuts import render
from django.db.models import Sum, F
from django.shortcuts import get_object_or_404
from django.views.decorators.cache import cache_page

from mainapp.models import Country, TimeSeries, MainTable


def total_active(*args):
    if args:
        return MainTable.objects.filter(country_id=args).aggregate(Sum('active')).get('active__sum')
    else:
        return MainTable.objects.aggregate(Sum('active')).get('active__sum')


def total_deaths(*args):
    if args:
        return MainTable.objects.filter(country_id=args).aggregate(Sum('deaths')).get('deaths__sum')
    else:
        return MainTable.objects.aggregate(Sum('deaths')).get('deaths__sum')


def total_recovered(*args):
    if args:
        return MainTable.objects.filter(country_id=args).aggregate(Sum('recovered')).get('recovered__sum')
    return MainTable.objects.aggregate(Sum('recovered')).get('recovered__sum')


def total_confirmed(*args):
    if args:
        return MainTable.objects.filter(country_id=args).aggregate(Sum('confirmed')).get('confirmed__sum')
    return MainTable.objects.aggregate(Sum('confirmed')).get('confirmed__sum')


def index(request):
    labels = []
    data_confirmed = []
    data_deaths = []
    data_recovered = []

    queryset = TimeSeries.objects.all().values('last_update'). \
        annotate(Sum('confirmed'), Sum('deaths'), Sum('recovered'))

    for day in queryset:
        labels.append('{:%d/%m}'.format(day['last_update']))
        data_confirmed.append(day['confirmed__sum'] / 1000)
        data_deaths.append(day['deaths__sum'] / 1000)
        data_recovered.append(day['recovered__sum'] / 1000)

    countries = Country.objects.all()

    covid_total_timeline = [
        {
            "confirmed": day['confirmed__sum'],
            "deaths": day['deaths__sum'],
            "recovered": day['recovered__sum'],
            "date": day['last_update'].strftime('%Y-%m-%d')
        }
        for day in queryset
    ]

    covid_world_timeline = [
        {
            "date": day['last_update'].strftime('%Y-%m-%d'),
            "list": [
                {
                    "confirmed": data['confirmed__sum'],
                    "deaths": data['deaths__sum'],
                    "recovered": data['recovered__sum'],
                    "id": data['country__iso_alpha_2']
                }
                for data in
                TimeSeries.objects.filter(last_update=day['last_update']).values('country__iso_alpha_2').
                    annotate(Sum('confirmed'), Sum('deaths'), Sum('recovered'))
                if data['country__iso_alpha_2']
            ]
        }
        for day in queryset
    ]

    context = {
        'labels': labels,
        'data_confirmed': data_confirmed,
        'data_deaths': data_deaths,
        'data_recovered': data_recovered,
        'countries': countries,
        'covid_total_timeline': covid_total_timeline,
        'covid_world_timeline': covid_world_timeline,
        'active': total_active(),
        'deaths': total_deaths(),
        'recovered': total_recovered(),
        'confirmed': total_confirmed(),
    }

    return render(request, 'mainapp/index.html', context)


def country_page(request, pk):
    country = get_object_or_404(Country, pk=pk)
    countries = Country.objects.all()

    queryset = TimeSeries.objects.filter(country_id=pk).values('last_update'). \
        annotate(Sum('confirmed'), Sum('deaths'), Sum('recovered'))

    chart_data = [
        {
            "date": day['last_update'].strftime('%m-%d'),
            "confirmed": day['confirmed__sum'],
            "recovered": day['recovered__sum'],
            "deaths": day['deaths__sum'],
        }
        for day in queryset
    ]
    print(chart_data)

    context = {
        'country_name': country.country,
        'countries': countries,
        'chart_data': chart_data,

        'active': total_active(pk),
        'deaths': total_deaths(pk),
        'recovered': total_recovered(pk),
        'confirmed': total_confirmed(pk),
    }

    return render(request, 'mainapp/country_page.html', context)

simple_prognozer/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Mannat Themes">
        <meta name="keyword" content="">

        <title>Chronologic of Coronavirus</title>

        <!-- Chart Resources -->
        {% block chart-resources %}
        {% endblock %}

        <!-- Theme icon -->
        <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

        <link href="{% static 'assets/plugins/morris-chart/morris.css' %}" rel="stylesheet">
        <!-- Theme Css -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/slidebars.min.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/menu.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    </head>

    <body class="sticky-header">
        <section>
            <!-- sidebar left start-->
            <div class="sidebar-left">
                <div class="sidebar-left-info">

                    <!--sidebar nav start-->
                    <ul class="side-navigation">
                        <li>
                            <h3 class="navigation-title">Navigation</h3>
                        </li>
                        {% block sidebar-menu-list-nav %}
                        {% endblock %}
                        <li class="menu-list"><a href="#"><i class="mdi mdi-map" aria-hidden="true"></i><span>Countries</span></a>
                            <ul class="child-list">

                                {% for country in countries %}
                                <li><a href="{% url 'mainapp:country_page' country.pk %}">
                                    {{ country.country }}
                                </a></li>
                                {% endfor %}

                            </ul>
                        </li>
                    </ul><!--sidebar nav end-->
                </div>
            </div><!-- sidebar left end-->

            <!-- body content start-->
            <div class="body-content">
                <!-- header section start-->
                <div class="header-section">
                    <!--logo and logo icon start-->
                    <div class="logo">
                        <a href="">
                            <span class="logo-img">
                                <img src="{% static 'img/logo.png' %}" alt="" height="46">
                            </span>
                            <!--<i class="fa fa-maxcdn"></i>-->
                            <span class="brand-name">ChronoCorona</span>
                        </a>
                    </div>

                    <!--toggle button start-->
                    <a class="toggle-btn"><i class="ti ti-menu"></i></a>
                    <!--toggle button end-->

                    <!--header1 start-->
                    {% block header1 %}
                    {% endblock %}
                    <!--header1 end-->
                </div>
                <!-- header section end-->

                <div class="container-fluid">
                    <!--header2 start-->
                    {% block header2 %}
                    {% endblock %}
                    <!--header2 end-->

                    {% block cases %}
                        <div class="cases">

                            <div class="confirmed-box">
                                <p>Confirmed:</p>
                                <p class="confirmed">{{ confirmed }}</p>
                            </div>

                            <div class="recovered-box">
                                <p>Recovered:</p>
                                <p class="recovered">
                                    {{ recovered }}</p>
                            </div>

                            <div class="deaths-box">
                                <p>Deaths:</p>
                                <p class="deaths">{{ deaths }}</p>
                            </div>

                            <div class="active-box">
                                <p>Active:</p>
                                <p class="active">{{ active }}</p>
                            </div>

                        </div>
                    {% endblock %}

                    <!--chart.js start-->
                    {% block chart-js %}
                    {% endblock %}
                    <!--chart.js end-->
                    <div class="text">
                        <p>
                        В мире не осталось людей, кто не слышал бы о бушующей пандемии коронавируса. Волна данного заболевания охватила весь земной шар. Вначале многие отнеслись весьма скептически к данной угрозе, а в последствии, поменяв свой взгляд на ситуацию, уже мало чем могли помочь. На сегодня статистика зараженных и умерших от данного заболевания, оставляет желать лучшего. Коронавирусу уже присвоен красный уровень опасности, он унес жизни более 624 тысячи людей по всему миру и продолжает убивать дальше.</p>
                        <p>Однако, медики нашли первые способы противостоять коронавирусу. И несмотря на то, что статистика заражений коронавирусом говорит о том, что число зараженных по всему миру уже превысило порог в 15 миллионов человек и продолжает расти, инфекцию все же удалось притормозить. Сегодня люди уже не так боятся выходить на улицу без средств защиты, так как зараженных стало намного меньше. Однако, это заблуждение. Коронавирус все еще не побежден, и он не спит!</p>
                        <p>Основными мерами защиты от коронавируса являются маски, перчатки и соблюдение дистанции между людьми не менее двух метров. Так же, к числу мер борьбы, относят и разрабатывающуюся в мире вакцину. По некоторым данным, вакцина уже тестируется на добровольцах, но результаты борьбы лекарства и коронавируса держатся пока в секрете. Тем временем, о коронавирусе и мерах борьбы с ним можно увидеть и услышать на каждом шагу. Правительство и медики продолжают предупреждать об опасности заболевания. Коронавирусу посвящены многие телепередачи, блоги и статьи. И хотя режим карантина снят во многих странах, людям рекомендуется соблюдать все возможные меры предосторожности.</p>
                        <p>Тем временем не стоит забывать и о приближающейся поре осенних инфекций. Наряду с сезонными заболеваниями, мир продолжает говорить и о коронавирусе и о возможной повторной вспышке. Прогнозируют, что коронавирусу предстоит еще как минимум раз заставить людей посидеть дома. Так что, маски и перчатки возможно нам еще пригодятся!</p>
                        <p>Данные берутся из Университета Джонса Хопкинса и Роспотребнадзора. Примечательно, что по мировым показателям сведения о коронавирусе Роспотребнадзора и американского университета иногда отличаются.</p>
                        <p>Так кто же входит в круг потенциальных жертв коронавирусов? Прежде всего те, кто живет в многоквартирных домах, кто работает в сфере обслуживания и, конечно, те, кто работает в непосредственном контакте с зараженными. Дети тоже являются частыми переносчиками данного заболевания, хотя сами могут болеть в легкой форме. Коронавирусу можно дать хороший отпор, если все будут соблюдать элементарные правила. Тогда, возможно, можно будет избежать повторной вспышки.</p>
                        <p>А пока у нас есть небольшая передышка, медики советуют, укреплять свой иммунитет. Чаще гулять (желательно подальше от большого скопления людей), правильно питаться и сохранять хороший настрой.</p>
                        <p>Люди недоумевают, почему некоторые переносят инфекцию коронавируса почти не замечая этого, тогда как других, еле удается спасти. Переработав разную информацию о коронавирусе, можно сказать, что основным фактором защиты служит иммунитет и отсутствие сопутствующих заболеваний пациента. Но, как говорят медики, не малое значение при коронавирусе играет сам настрой и желания вылечивакцина против ться самого заболевшего.</p>
            </div>

            </div><!--end container-->

                <!--footer section start-->
                <footer class="footer">
                    <p>
                        2020 &copy; Внимание! Ответственность автора.
                        <br>
                        Данный сайт не распространяет недостоверную информацию о коронавирусе.
                        Вся информация основана на простом прогнозировании и не претендует на достоверность,
                        так как реальное распространение коронавирусной инфекции зависит от разных факторов,
                        которые могут меняться каждый день. Авторы не несут ответственность за несбывшиеся прогнозы.
                    </p>

                </footer>
                <!--footer section end-->
            </div>
            <!--end body content-->
        </section>

        <!-- jQuery -->
        <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery-migrate.js' %}"></script>
        <script src="{% static 'assets/js/modernizr.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'assets/js/slidebars.min.js' %}"></script>

        <!--plugins js-->
        <script src="{% static 'assets/plugins/counter/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'assets/plugins/waypoints/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'assets/plugins/sparkline-chart/jquery.sparkline.min.js' %}"></script>
        <script src="{% static 'assets/pages/jquery.sparkline.init.js' %}"></script>

        <script src="{% static 'assets/plugins/chart-js/Chart.bundle.js' %}"></script>
        <script src="{% static 'assets/plugins/morris-chart/raphael-min.js' %}"></script>
        <script src="{% static 'assets/plugins/morris-chart/morris.js' %}"></script>
        <script src="{% static 'assets/pages/dashboard-init.js' %}"></script>

        <!--app js-->
        <script src="{% static 'assets/js/jquery.app.js' %}"></script>
        <script>
            jQuery(document).ready(function($) {
                $('.counter').counterUp({
                delay: 100,
                time: 1200
                });
            });
        </script>

        <!--chart-js-script-->
        {% block chart-js-script %}
        {% endblock %}
    </body>
</html>

simple_prognozer/mainapp/templates/mainapp/country_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block chart-resources %}
    <!-- Resources -->
    <script src="{% static 'assets/js/amcharts/core.js' %}"></script>
    <script src="{% static 'assets/js/amcharts/charts.js' %}"></script>
    <script src="{% static 'assets/js/amcharts/material.js' %}"></script>
    <script src="{% static 'assets/js/amcharts/animated.js' %}"></script>
{% endblock %}

{% block sidebar-menu-list-nav %}
    <li>
        <a href="{% url 'mainapp:index' %}">To index</a>
    </li>
{% endblock %}

{% block header1 %}
    <h1 class="header-1">Chronologic of Coronavirus WorldWide</h1>
{% endblock %}

{% block header2 %}
    <h2 class="header-2">{{ country_name }}</h2>
{% endblock %}

{% block chart-js %}

    <!-- Styles -->
    <style>
    #chartdiv {
      width: 100%;
      height: 500px;
    }

    </style>
    <!-- HTML -->
    <div id="chartdiv"></div>

{% endblock %}

{% block chart-js-script %}

    <!-- Chart code -->
    <script>
        am4core.ready(function() {

        // Themes begin
        am4core.useTheme(am4themes_material);
        am4core.useTheme(am4themes_animated);
        // Themes end

        var chart = am4core.create("chartdiv", am4charts.XYChart);

        chart.data = {{ chart_data|safe }};

        var dateAxis = chart.xAxes.push(new am4charts.DateAxis());

        var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
        valueAxis.tooltip.disabled = true;

        var series = chart.series.push(new am4charts.LineSeries());
        series.dataFields.dateX = "date";
        series.name = "confirmed";
        series.dataFields.valueY = "confirmed";
        series.tooltipHTML = "<img src='{% static 'img/sick.png' %}' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>{valueY.value}</b></span>";
        series.tooltipText = "[#000]{valueY.value}[/]";
        series.tooltip.background.fill = am4core.color("#FFF");
        series.tooltip.getStrokeFromObject = true;
        series.tooltip.background.strokeWidth = 3;
        series.tooltip.getFillFromObject = false;
        series.fillOpacity = 0.6;
        series.strokeWidth = 2;
        series.stacked = true;

        var series2 = chart.series.push(new am4charts.LineSeries());
        series2.name = "recovered";
        series2.dataFields.dateX = "date";
        series2.dataFields.valueY = "recovered";
        series2.tooltipHTML = "<img src='{% static 'img/glitter.png' %}' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>{valueY.value}</b></span>";
        series2.tooltipText = "[#000]{valueY.value}[/]";
        series2.tooltip.background.fill = am4core.color("#FFF");
        series2.tooltip.getFillFromObject = false;
        series2.tooltip.getStrokeFromObject = true;
        series2.tooltip.background.strokeWidth = 3;
        series2.sequencedInterpolation = true;
        series2.fillOpacity = 0.6;
        series2.stacked = true;
        series2.strokeWidth = 2;

        var series3 = chart.series.push(new am4charts.LineSeries());
        series3.name = "deaths";
        series3.dataFields.dateX = "date";
        series3.dataFields.valueY = "deaths";
        series3.tooltipHTML = "<img src='{% static 'img/dead.png' %}' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>{valueY.value}</b></span>";


        series3.tooltipText = "[#000]{valueY.value}[/]";
        series3.tooltip.background.fill = am4core.color("#FFF");
        series3.tooltip.getFillFromObject = false;
        series3.tooltip.getStrokeFromObject = true;
        series3.tooltip.background.strokeWidth = 3;
        series3.sequencedInterpolation = true;
        series3.fillOpacity = 0.6;
        series3.defaultState.transitionDuration = 1000;
        series3.stacked = true;
        series3.strokeWidth = 2;

        chart.cursor = new am4charts.XYCursor();
        chart.cursor.xAxis = dateAxis;
        chart.scrollbarX = new am4core.Scrollbar();

        // Add a legend
        chart.legend = new am4charts.Legend();
        chart.legend.position = "top";

        }); // end am4core.ready()
    </script>
{% endblock %}

simple_prognozer/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block chart-resources %}
    <!-- Chart.js -->
    <script src="{% static 'assets/js/chart_js/chart.min.js' %}"></script>
{% endblock %}

{% block header1 %}
    <h1 class="header-1">Chronologic of Coronavirus WorldWide</h1>
{% endblock %}

{% block header2 %}
    <h2 class="header-2">General Statistics</h2>
{% endblock %}

{% block chart-js %}
    {% include 'mainapp/includes/inc__world_map.html' %}

    <div id="container" style="width: 75%;">
        <canvas id="confirmedChart"></canvas>
        <canvas id="deathChart"></canvas>
        <canvas id="recoveredChart"></canvas>
    </div>
{% endblock %}

{% block chart-js-script %}
    <script>
        var config_confirmed = {
            type: 'line',
            data: {
                datasets: [{
                    data: {{ data_confirmed|safe }},
                    label: 'Confirmed'
                }],
                labels: {{ labels|safe }}
            },
            options: {
                responsive: true
            }
        };
        var config_deaths = {
            type: 'line',
            data: {
                datasets: [{
                    data: {{ data_deaths|safe }},
                    label: 'Deaths'
                }],
                labels: {{ labels|safe }}
            },
            options: {
                responsive: true
            }
        };
        var config_recovered = {
            type: 'line',
            data: {
                datasets: [{
                    data: {{ data_recovered|safe }},
                    label: 'Recovered'
                }],
                labels: {{ labels|safe }}
            },
            options: {
                responsive: true
            }
        };

        window.onload = function () {
            var ctx = document.getElementById('confirmedChart').getContext('2d');
            window.myPie = new Chart(ctx, config_confirmed);
            var ctx_1 = document.getElementById('deathChart').getContext('2d');
            window.myPie = new Chart(ctx_1, config_deaths);
            var ctx_2 = document.getElementById('recoveredChart').getContext('2d');
            window.myPie = new Chart(ctx_2, config_recovered);
        };
    </script>
{% endblock %}